### ISSUE TITLE
missing `tqdm` in the dep list

### ISSUE THREAD

**Issue by chenrui333** [ivan-sincek/forbidden#4]
👋 while building 12.2 release, it looks like `tqdm` is  missing in the dep list.

```
$ pipgrip --tree forbidden
forbidden (12.2)
├── alive-progress>=3.1.5 (3.1.5)
│   ├── about-time==4.2.1 (4.2.1)
│   └── grapheme==0.6.0 (0.6.0)
├── colorama>=0.4.6 (0.4.6)
├── datetime>=5.2 (5.5)
│   ├── pytz (2024.2)
│   └── zope-interface (7.0.3)
│       └── setuptools (74.1.2)
├── pycurl>=7.45.2 (7.45.3)
├── pyjwt>=2.7.0 (2.9.0)
├── regex>=2023.8.8 (2024.9.11)
├── requests>=2.31.0 (2.32.3)
│   ├── certifi>=2017.4.17 (2024.8.30)
│   ├── charset-normalizer<4,>=2 (3.3.2)
│   ├── idna<4,>=2.5 (3.8)
│   └── urllib3<3,>=1.21.1 (2.2.2)
├── tabulate>=0.9.0 (0.9.0)
└── termcolor>=1.1.0 (2.4.0)
```

relates to https://github.com/Homebrew/homebrew-core/pull/187646

**Comment by ivans-affinidi** [comment]
Hi @chenrui333,

Thank you for highlighting this issue!

I was experimenting with different progress bars, and `tqdm` import is a leftover code. I will remove it and release the v12.3 later today.

Kind regards,
Ivan.

**Comment by ivan-sincek** [comment]
Hi @chenrui333,

Thank you for highlighting this issue!

I was experimenting with different progress bars, and `tqdm` import is a leftover code. I will remove it and release the v12.3 later today.

Kind regards,
Ivan.

**Comment by ivan-sincek** [comment]
Hi @chenrui333;

v12.3 has been published!

Best regards,
Ivan.

**Comment by chenrui333** [comment]
got you, thanks!
